import jsPDF from 'jspdf';

const generateHtmlBrief = (messages, officerName, title) => {
  const messageHtml = messages.map(m => `
    <div style="margin-bottom: 20px; border-bottom: 1px solid #ddd; padding-bottom: 10px;">
      <h3 style="color: ${m.role === 'user' ? '#1e3a8a' : '#c29207'}; font-size: 12px; margin-bottom: 5px; font-family: sans-serif;">
        ${m.role === 'user' ? 'OFFICER QUERY' : 'KAVACH AI RESPONSE'}
      </h3>
      <p style="font-size: 14px; line-height: 1.5; color: #333; white-space: pre-wrap; margin: 0; font-family: sans-serif;">${m.content}</p>
      ${m.citations?.length ? `
        <p style="font-size: 11px; color: #666; font-style: italic; margin-top: 5px; font-family: sans-serif;">
          Sources: ${m.citations.map(c => c.label || c.id).join(', ')}
        </p>
      ` : ''}
    </div>
  `).join('');

  return `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #222; }
          .header { background: #0a1f44; color: #c9a227; padding: 20px; text-align: center; border-radius: 8px; margin-bottom: 30px; }
          .header h1 { margin: 0; font-size: 24px; font-family: serif; }
          .header p { margin: 5px 0 0 0; font-size: 12px; color: #ede5cf; font-family: monospace; }
          .meta { font-size: 12px; color: #666; margin-bottom: 20px; border-bottom: 2px solid #c9a227; padding-bottom: 10px; font-family: sans-serif; }
          .disclaimer { font-size: 10px; color: #7f1d24; font-style: italic; border-top: 1px solid #ccc; padding-top: 15px; margin-top: 40px; font-family: sans-serif; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>KAVACH AI</h1>
          <p>SAFEGUARDING KARNATAKA — Karnataka State Police</p>
        </div>
        <div class="meta">
          <strong>${title}</strong><br/>
          Generated by: ${officerName || 'Unknown Officer'} | Date: ${new Date().toLocaleString('en-IN')}
        </div>
        <div class="content">
          ${messageHtml}
        </div>
        <div class="disclaimer">
          DISCLAIMER: This document is generated by KAVACH AI, an investigative assistance tool. All factual claims are grounded in retrieved case records and cited above. This export is an investigative aid only and must be independently verified before use in any official filing, chargesheet, or court proceeding.
        </div>
      </body>
    </html>
  `;
};

// Exports a KAVACH AI conversation thread as a formatted PDF, 
// using server-side Zoho Catalyst SmartBrowz when available, 
// or falling back to client-side jsPDF for local development.
export async function exportConversationPdf({ messages, officerName, title = 'KAVACH AI — Conversation Export' }) {
  // If running in Zoho Catalyst environment
  if (window.catalyst) {
    try {
      console.log('[KAVACH] Generating PDF server-side using Zoho Catalyst SmartBrowz...');
      const htmlContent = generateHtmlBrief(messages, officerName, title);
      const response = await fetch('/api/generate-pdf', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          html: htmlContent,
          filename: `KAVACH_Brief_${Date.now()}.pdf`
        })
      });
      if (!response.ok) throw new Error('SmartBrowz generation request failed');
      
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `KAVACH_Brief_${Date.now()}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
      return;
    } catch (e) {
      console.warn('[KAVACH] Server-side PDF generation failed, falling back to local jsPDF:', e);
    }
  }

  // Fallback to client-side jsPDF
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = 56;

  doc.setFillColor(10, 31, 68); // navy-900
  doc.rect(0, 0, pageWidth, 70, 'F');
  doc.setTextColor(201, 162, 39); // gold-500
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('KAVACH AI', margin, 32);
  doc.setTextColor(230, 205, 125);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('SAFEGUARDING KARNATAKA — Karnataka State Police', margin, 48);

  y = 96;
  doc.setTextColor(20, 20, 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(title, margin, y);
  y += 18;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(90, 90, 90);
  doc.text(`Generated by: ${officerName || 'Unknown Officer'}   |   ${new Date().toLocaleString('en-IN')}`, margin, y);
  y += 20;
  doc.setDrawColor(201, 162, 39);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  const maxWidth = pageWidth - margin * 2;

  messages.forEach((m) => {
    const label = m.role === 'user' ? 'OFFICER QUERY' : 'KAVACH AI RESPONSE';
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(m.role === 'user' ? 30 : 168, m.role === 'user' ? 60 : 130, m.role === 'user' ? 120 : 30);
    if (y > 760) { doc.addPage(); y = 56; }
    doc.text(label, margin, y);
    y += 14;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(20, 20, 20);
    const lines = doc.splitTextToSize(m.content || '', maxWidth);
    lines.forEach((line) => {
      if (y > 780) { doc.addPage(); y = 56; }
      doc.text(line, margin, y);
      y += 13;
    });

    if (m.citations?.length) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      const citeLine = `Sources: ${m.citations.map((c) => c.label || c.id).join(', ')}${typeof m.confidence === 'number' ? ` · Confidence: ${Math.round(m.confidence * 100)}%` : ''}`;
      const citeLines = doc.splitTextToSize(citeLine, maxWidth);
      citeLines.forEach((line) => {
        if (y > 780) { doc.addPage(); y = 56; }
        doc.text(line, margin, y);
        y += 11;
      });
    }
    y += 14;
  });

  if (y > 740) { doc.addPage(); y = 56; }
  y += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 16;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(150, 30, 30);
  const disclaimer = doc.splitTextToSize(
    'DISCLAIMER: This document is generated by KAVACH AI, an investigative assistance tool. All factual claims are grounded in retrieved case records and cited above. This export is an investigative aid only and must be independently verified before use in any official filing, chargesheet, or court proceeding.',
    maxWidth
  );
  doc.text(disclaimer, margin, y);

  doc.save(`KAVACH_Conversation_${Date.now()}.pdf`);
}
