import jsPDF from 'jspdf';

// Exports a KAVACH AI conversation thread (or a single investigation brief)
// as a formatted PDF, per the KSP Datathon 2026 "PDF export of conversation
// history" requirement. Government-branded header/footer with a disclaimer
// on every export reinforcing that AI output is an investigative aid, not
// an evidentiary finding.
export function exportConversationPdf({ messages, officerName, title = 'KAVACH AI — Conversation Export' }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = 56;

  doc.setFillColor(10, 31, 68); // navy-900
  doc.rect(0, 0, pageWidth, 70, 'F');
  doc.setTextColor(201, 162, 39); // gold-500
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('KAVACH AI', margin, 32);
  doc.setTextColor(230, 205, 125);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('SAFEGUARDING KARNATAKA — Karnataka State Police', margin, 48);

  y = 96;
  doc.setTextColor(20, 20, 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(title, margin, y);
  y += 18;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(90, 90, 90);
  doc.text(`Generated by: ${officerName || 'Unknown Officer'}   |   ${new Date().toLocaleString('en-IN')}`, margin, y);
  y += 20;
  doc.setDrawColor(201, 162, 39);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  const maxWidth = pageWidth - margin * 2;

  messages.forEach((m) => {
    const label = m.role === 'user' ? 'OFFICER QUERY' : 'KAVACH AI RESPONSE';
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(m.role === 'user' ? 30 : 168, m.role === 'user' ? 60 : 130, m.role === 'user' ? 120 : 30);
    if (y > 760) { doc.addPage(); y = 56; }
    doc.text(label, margin, y);
    y += 14;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(20, 20, 20);
    const lines = doc.splitTextToSize(m.content || '', maxWidth);
    lines.forEach((line) => {
      if (y > 780) { doc.addPage(); y = 56; }
      doc.text(line, margin, y);
      y += 13;
    });

    if (m.citations?.length) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      const citeLine = `Sources: ${m.citations.map((c) => c.label || c.id).join(', ')}${typeof m.confidence === 'number' ? ` · Confidence: ${Math.round(m.confidence * 100)}%` : ''}`;
      const citeLines = doc.splitTextToSize(citeLine, maxWidth);
      citeLines.forEach((line) => {
        if (y > 780) { doc.addPage(); y = 56; }
        doc.text(line, margin, y);
        y += 11;
      });
    }
    y += 14;
  });

  if (y > 740) { doc.addPage(); y = 56; }
  y += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 16;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(150, 30, 30);
  const disclaimer = doc.splitTextToSize(
    'DISCLAIMER: This document is generated by KAVACH AI, an investigative assistance tool. All factual claims are grounded in retrieved case records and cited above. This export is an investigative aid only and must be independently verified before use in any official filing, chargesheet, or court proceeding.',
    maxWidth
  );
  doc.text(disclaimer, margin, y);

  doc.save(`KAVACH_Conversation_${Date.now()}.pdf`);
}
